In [ ]:
import pandas as pd

df = pd.read_csv('../data/processed/processed_data.csv')

df.head()

In [2]:
import pandas as pd

df = pd.read_csv('../data/processed/processed_data.csv')

df.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V22,V23,V24,V25,V26,V27,V28,Class,scaled_amount,scaled_time
0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,...,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,0,1.783274,-0.994983
1,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,...,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,0,-0.269825,-0.994983
2,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,...,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,0,4.983721,-0.994972
3,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,...,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,0,1.418291,-0.994972
4,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,...,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,0,0.670579,-0.994960

In [ ]:
df_sample = df.sample(50000, random_state=42)

X = df_sample.drop('Class', axis=1)

from sklearn.neighbors import LocalOutlierFactor

lof = LocalOutlierFactor(n_neighbors=20, contamination=0.01)

df_sample['lof_anomaly'] = lof.fit_predict(X)

df_sample.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V23,V24,V25,V26,V27,V28,Class,scaled_amount,scaled_time,lof_anomaly
43428,-16.526507,8.584972,-18.649853,9.505594,-13.793819,-2.832404,-16.701694,7.517344,-8.507059,-14.110184,...,-2.358579,0.673461,-1.413700,-0.462762,-2.018575,-1.042804,1,4.781527,-0.507372,1
49906,0.339812,-2.743745,-0.134070,-1.385729,-1.451413,1.015887,-0.524379,0.224060,0.899746,-0.565012,...,-0.526819,-1.156992,0.311211,-0.746647,0.040996,0.102038,0,6.960386,-0.474994,1
29474,1.399590,-0.590701,0.168619,-1.029950,-0.539806,0.040444,-0.712567,0.002299,-0.971747,0.756801,...,-0.166639,-0.810250,0.505083,-0.232340,0.011409,0.004634,0,0.125760,-0.578108,1
276481,-0.432071,1.647895,-1.669361,-0.349504,0.785785,-0.630647,0.276990,0.586025,-0.484715,-1.376648,...,-0.178642,-0.017171,-0.207392,-0.157756,-0.237386,0.001934,0,-0.286453,0.968421,1
278846,2.014160,-0.137394,-1.015839,0.327269,-0.182179,-0.956571,0.043241,-0.160746,0.363241,0.259452,...,0.347045,0.061561,-0.360196,0.174730,-0.078043,-0.070571,0,-0.294977,0.984281,1

In [4]:
from sklearn.metrics import classification_report

df_sample['lof_converted'] = df_sample['lof_anomaly'].apply(lambda x: 1 if x == -1 else 0)

print(classification_report(df_sample['Class'], df_sample['lof_converted']))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99     49917
           1       0.02      0.10      0.03        83

    accuracy                           0.99     50000
   macro avg       0.51      0.54      0.51     50000
weighted avg       1.00      0.99      0.99     50000